### ISSUE TITLE
barcode error

### ISSUE THREAD

**Issue by lgmp315** [singleron-RD/CeleScope#103]
![barcode get_mismatch_dict报错](https://user-images.githubusercontent.com/98027401/156692249-d368c8f7-fdc5-4a54-b381-1430dec7d5db.png)
![第一次报错](https://user-images.githubusercontent.com/98027401/156692282-9b339972-22d2-4a9c-a3c5-f798a632f57f.png)
![第二次报错](https://user-images.githubusercontent.com/98027401/156692288-81cb8f44-1627-4242-abfa-8ab20cc638c2.png)

dear friend, I use my rna data to run on celescope rna , the error turns out several time at the same position. And I change my data it comes up with the same problem.

**Comment by zhouyiqi91** [comment]
It seems that at least one read in your R2 fastq file has truncated quality string. You can use the following script to find the read
```
zcat {R2_fq.gz} | paste - - - - | awk -F"\t" '{ if (length($2) != length($4)) print (NR,$0) }'
```

**Comment by lgmp315** [comment]
![03d7c2bd556e155b206bd19772458be](https://user-images.githubusercontent.com/98027401/156877418-f1a46bb8-ee89-46fa-9d89-413b3c769010.jpg)
dEAR fRIENd. when using multi_rna . it stucks at this line for quiet a long time and dead at last, do you know whats the problem?

**Comment by zhouyiqi91** [comment]
It was actually running the pipeline. If the fastq file can be found under `{sample}/01.barcode` and the size keeps increasing during runtime, it means there is no problem. 
If the program is killed after running for a period of time, maybe your server has a program running time limit?
