### ISSUE TITLE
why the chemistry scopeV2.0.1 have lower Valid Reads of just 22% than other chemistries like scopeV2.1.1 or scopeV2.2.1?

### ISSUE THREAD

**Issue by XiaohuanQin61** [singleron-RD/CeleScope#108]

**Comment by zhouyiqi91** [comment]
Different chemistry corresponds to different beads pattern. See https://github.com/singleron-RD/CeleScope/blob/master/docs/chemistry.md for more details.
It is recommended to use `--chemistry auto` to auto-detect the chemistry.

**Comment by XiaohuanQin61** [comment]
> Different chemistry corresponds to different beads pattern. See https://github.com/singleron-RD/CeleScope/blob/master/docs/chemistry.md for more details. It is recommended to use `--chemistry auto` to auto-detect the chemistry.
Yeah, at first time, I didn't specify the chemistry of each library and all of them were auto-detected. But all of the libraries of scopeV2.0.1 can only map to 1 gene per cell. It's so odd! I wanna know if there are some parameters help me to solve this problem?

**Comment by zhouyiqi91** [comment]
How many samples do you have and what are their auto-detected chemistry?

**Comment by XiaohuanQin61** [comment]
There are 24 samples and all of them are auto-detected. Three of them are  scopeV2.0.1, One is scopeV2.1.1. The rest are scopeV2.2.1.

________________________________
发件人: Tony Zhou ***@***.***>
发送时间: Tuesday, March 8, 2022 4:03:30 PM
收件人: singleron-RD/CeleScope ***@***.***>
抄送: MugenQin ***@***.***>; Author ***@***.***>
主题: Re: [singleron-RD/CeleScope] why the chemistry scopeV2.0.1 have lower Valid Reads of just 22% than other chemistries like scopeV2.1.1 or scopeV2.2.1? (Issue #108)


How many samples do you have and what are their auto-detected chemistry?

―
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsingleron-RD%2FCeleScope%2Fissues%2F108%23issuecomment-1061507603&data=04%7C01%7C%7Ca47b815703114be549fb08da00da2317%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823234138624247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TXAClJTxdFwSOxhD%2FXvbKAHstL%2Fwx%2BwajeQTji8erk0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUXAXTFM2YAPKJZ2JXMKNQLU64CVFANCNFSM5QFN5WGQ&data=04%7C01%7C%7Ca47b815703114be549fb08da00da2317%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823234138624247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8DM%2FILUOMwNv9in1K4M%2F%2Fb8JTnwRBUK8s91axRDc%2BDk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca47b815703114be549fb08da00da2317%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823234138624247%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wBbvQCyh%2B%2F%2B3hNxgtdv7Iu3n2TWQoKZ9q%2FleiRUSLtE%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca47b815703114be549fb08da00da2317%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637823234138780468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FxCKr5Uhal7d5p15YysYDxSU%2BIdqz7FD5XQTbpfCk9w%3D&reserved=0>.

**Comment by zhouyiqi91** [comment]
It's weird. If the samples are from the same batch, they should have the same chemistry. Also scopeV2.0.1 and scopeV2.1.1 are old versions that are no longer in use.
Can you pick a sample detected as scopeV2.0.1 and send the first 10000 reads (first 40000 lines) of R1 reads here? (github comments can have attachments)

**Comment by XiaohuanQin61** [comment]
[R1.txt](https://github.com/singleron-RD/CeleScope/files/8204608/R1.txt)
Can you see this one?

**Comment by zhouyiqi91** [comment]
After analysis, I found that none of the 10,000 reads fit any chemistry.

The reason why some reads are detected as scopeV2.0.1 is because the automatic detection method of chemistry has been changed in the celescope v1.7.* version. The conditions for detecting scopeV2.0.1 are too loose, and only the position of polyT is required to match. Among the 10,000 reads, the polyT positions of some of the reads coincided.

The 10,000 reads above fit a pattern: 21bp random oligo (probably some kind of barcode) + polyT. This doesn't match any chemistry from Singleron. A possible explanation is that the three fastqs detected as scopeV2.0.1 are from another platform (nor 10X as far as I know: 10X is 16bp barcode + 10 or 12 bp UMI).

**Comment by zhouyiqi91** [comment]
I am also curious about the 22% valid reads for samples detected as scopeV2.0.1. In theory, the valid reads of these three samples should be close to 0. Can you send an HTML report to `zhouyiqi@singleronbio.com` ? Thanks

**Comment by XiaohuanQin61** [comment]
> 

Get it! Thank you so much! I will check these libraries. I think some other libraries which can not get the reports may have the same reason.

**Comment by zhouyiqi91** [comment]
> I am also curious about the 22% valid reads for samples detected as scopeV2.0.1. In theory, the valid reads of these three samples should be close to 0. Can you send an HTML report to `zhouyiqi@singleronbio.com` ? Thanks

After checking the HTML report, `22` is the `number of vaild reads`, not the `fraction of valid reads`. The `fraction of valid reads` is close to 0%.

**Comment by XiaohuanQin61** [comment]
> > I am also curious about the 22% valid reads for samples detected as scopeV2.0.1. In theory, the valid reads of these three samples should be close to 0. Can you send an HTML report to `zhouyiqi@singleronbio.com` ? Thanks
> 
> After checking the HTML report, `22` is the `number of vaild reads`, not the `fraction of valid reads`. The `fraction of valid reads` is close to 0%.

Thanks! I got that wrong.

**Comment by MugenQin** [comment]
> > I am also curious about the 22% valid reads for samples detected as scopeV2.0.1. In theory, the valid reads of these three samples should be close to 0. Can you send an HTML report to `zhouyiqi@singleronbio.com` ? Thanks
> 
> After checking the HTML report, `22` is the `number of vaild reads`, not the `fraction of valid reads`. The `fraction of valid reads` is close to 0%.

Thanks! I got that wrong.
