### ISSUE TITLE
pip install celescope failed!

### ISSUE THREAD

**Issue by FranChien** [singleron-RD/CeleScope#112]
after python version upgraded to 3.9.0, there is an error below!
ERROR: Could not build wheels for sorted-nearest, pyrle, which is required to install pyproject.toml-based projects

**Comment by zhouyiqi91** [comment]
I guess you are trying to use celescope 1.8.0 because version 1.8.0 upgraded python from 3.6 to 3.9
There are many reasons why build wheels failed, such as low gcc or pip version. A complete error log is required to solve this problem.
The easiest solution is to create another conda environment and reinstall celescope1.8.0.

**Comment by FranChien** [comment]
Thanks a lot! I figure out that the gcc version is not paired. I installed celescope after i uninstalled the gcc whose version is 9.4.0.

**Comment by ruffyp** [comment]
Hi, there,

I got an error when executing `pip install celescope --index https://pypi.tuna.tsinghua.edu.cn/simple` :

In file included from pysam/libchtslib.c:133:
      /.../anaconda3/envs/celescope/include/python3.9/Python.h:44:10: fatal error: crypt.h: No such file or directory
         44 | #include <crypt.h>
            |          ^~~~~~~~~
      compilation terminated.
      error: command '/.../anaconda3/envs/celescope/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pysam
  Building wheel for session-info (setup.py) ... done
  Created wheel for session-info: filename=session_info-1.0.0-py3-none-any.whl size=8023 sha256=52cc15b8b4c106fa9b5ba7445863ea26fdab5e3b82ec90dc8f86bc263d64c4db
  Stored in directory: /home/.../.cache/pip/wheels/6b/dd/79/ab42241fe1ba983661c59857e321da80daa6cc45c6d1807f69
Successfully built session-info
Failed to build pysam
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pysam)


And, before this, the following commands have been successfully executed:

```
wget https://raw.githubusercontent.com/singleron-RD/CeleScope/master/conda_pkgs.txt
conda create -n celescope -y --file conda_pkgs.txt
source activate celescope
```

So, how can I handle this error?

**Comment by zhouyiqi91** [comment]
> Hi, there,
> 
> I got an error when executing `pip install celescope --index https://pypi.tuna.tsinghua.edu.cn/simple` :
> 
> In file included from pysam/libchtslib.c:133: /.../anaconda3/envs/celescope/include/python3.9/Python.h:44:10: fatal error: crypt.h: No such file or directory 44 | #include <crypt.h> | ^~~~~~~~~ compilation terminated. error: command '/.../anaconda3/envs/celescope/bin/gcc' failed with exit code 1 [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for pysam Building wheel for session-info (setup.py) ... done Created wheel for session-info: filename=session_info-1.0.0-py3-none-any.whl size=8023 sha256=52cc15b8b4c106fa9b5ba7445863ea26fdab5e3b82ec90dc8f86bc263d64c4db Stored in directory: /home/.../.cache/pip/wheels/6b/dd/79/ab42241fe1ba983661c59857e321da80daa6cc45c6d1807f69 Successfully built session-info Failed to build pysam ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pysam)
> 
> And, before this, the following commands have been successfully executed:
> 
> ```
> wget https://raw.githubusercontent.com/singleron-RD/CeleScope/master/conda_pkgs.txt
> conda create -n celescope -y --file conda_pkgs.txt
> source activate celescope
> ```
> 
> So, how can I handle this error?

You can try to install pysam with `conda` first, then using `pip` to install celescope. On some platforms, using `pip` to install pysam will cause errors which is hard to fix.

**Comment by ruffyp** [comment]
It works, thanks for your help!
