### ISSUE TITLE
About celescope RNA barcode

### ISSUE THREAD

**Issue by 10KGenomics** [singleron-RD/CeleScope#119]
Hello, please ask a question about the celescope RNA barcode instruction. My instructions are as follows: celescope RNA barcode -- chemistry customized -- pattern C8U6C8U6T10 -- whitelist cellbarcode_ list. Txt --sample wt --fq1wt_ R1. fastq --fq2 WT_ R2. fastq --gzip --thread 20 --outdir 1-Barcode_ Out /, where cellbarcode_ list. Txt file is the sequence of 8bp barcode1 + 8bp barcode2, a total of 16bp long, but an error is reported, as follows:
![image](https://user-images.githubusercontent.com/67781404/164586254-23292d1d-115a-49ae-8c74-3aa4ea96a467.png)

**Comment by zhouyiqi91** [comment]
In this case, each line of the `--whitelist` should be 8bp, not 16bp.
If the whitelists of barcode1 and barcode2 are the same, then there is no need to write duplicate lines in the whitelist.
If not, write them seperately:
```
barcode1_1
barcode1_2
...
barcode2_1
barcode2_2
...

**Comment by 10KGenomics** [comment]
> 在这种情况下，每一行`--whitelist`应该是 8bp，而不是 16bp。 如果barcode1和barcode2的白名单相同，则白名单中不需要写重复行。 如果不是，请分别编写：
> 
> ```
> barcode1_1
> barcode1_2
> ...
> barcode2_1
> barcode2_2
> ...
> ```

Thank you very much, OK! Thank you for your reply!
