### ISSUE TITLE
compatibility with velocyto

### ISSUE THREAD

**Issue by shanshenbing** [singleron-RD/CeleScope#122]
after running CeleScope, I want to run velocyto and do Rna  velocity analysis. My code is like this:
dir_mk ${WORK_DIR}/result/${SAMPLE}/velocyto
cd ${WORK_DIR}/result/${SAMPLE}
velocyto run -b 05.count/${SAMPLE}_matrix_10X/barcodes.tsv -o ./velocyto ./03.star/${SAMPLE}_Aligned.sortedByCoord.out.bam ${mygtf}

Here is my CeleScope result dir:
![image](https://user-images.githubusercontent.com/42245493/166103904-b6ec47a5-4058-4247-a304-4c4f8914a4c4.png)

After I run the code, I got "OSError: The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag". 
NOTE:
the input bam for velocity should have:
1) Be sorted by mapping position. 
2) Represents either a single sample (multiple cells prepared using a certain barcode set in a single experiment) or single cell.
3) Contain an error corrected cell barcodes as a TAG named CB or XC.
4)Contain an error corrected molecular barcodes as a TAG named UB or XM.

Indeed, I can't find CB, XC,UB, XM tag in /03.star/${SAMPLE}_Aligned.sortedByCoord.out.bam header.
Can you help me get this info? Any suggestions will be apprepiated.

**Comment by zhouyiqi91** [comment]
You can use the bam files under 04.featureCounts which contain CB and UB tag.

**Comment by shanshenbing** [comment]
Thanks for your so rapid reply. I can run velocyto with 04.featureCounts/${SAMPLE}_name_sorted.bam now.

**Comment by shanshenbing** [comment]
Thanks for your so rapid reply. I can run&nbsp;velocyto with 04.featureCounts/${SAMPLE}_name_sorted.bam now.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tony ***@***.***&gt;; 
发送时间: 2022年4月30日(星期六) 晚上8:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [singleron-RD/CeleScope] compatibility with velocyto (Issue #122)





 
You can use the bam files under 04.featureCounts which contain CB and UB tag.
