### ISSUE TITLE
about celescope RNA featurescount !

### ISSUE THREAD

**Issue by 10KGenomics** [singleron-RD/CeleScope#124]
Dear sir:
Hello! I want to inquire about the celescope RNA featurescount instruction. My sample is the nucleus. In gene quantification, whether to select gene in parameter --gtf_type or add other instructions of featureCounts under --featureCounts_param. We look forward to your reply.

**Comment by zhouyiqi91** [comment]
You should use `--gtf_type gene`.

Note: multi_rna works for both single-cell RNA-Seq(scRNA-seq) and single-nucleus RNA-seq(snRNA-seq). The default settings are fine for scRNA-seq, but for snRNA-seq, you need to add --gtf_type gene to include reads mapped to intronic regions.
https://github.com/singleron-RD/CeleScope/blob/dev/docs/quick_start.md
