### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by h1106351165** [singleron-RD/CeleScope#127]
Hello, unfortunately, I found that python module import error would be reported on my server to install Celescope software following the tutorial.  It is very strange, I am sure that the version of all dependent  python packages are concordant.  Would you give some advises to solve this bug? Thanks!

**Comment by zhouyiqi91** [comment]
Could you please upload the log file and the command you used?

**Comment by wangxiv** [comment]
I have a similar problem:

  File "/data4/software/miniconda3/envs/celescope/lib/python3.9/site-packages/sklearn/__check_build/__init__.py", line 31, in raise_build_error
    raise ImportError(
ImportError: dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /data4/software/miniconda3/envs/celescope/lib/python3.9/site-packages/sklearn/__check_build:
__init__.py               setup.py                  _check_build.cpython-39-x86_64-linux-gnu.so
__pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

I had installed scikit-learn==1.1.3 use pip install scikit-learn==1.1.3.

**Comment by zhouyiqi91** [comment]
https://github.com/scikit-learn/scikit-learn/issues/14485#issuecomment-981704922

Going through the threads for other projects related to this issue, I see a common resolution is to upgrade their version of glibc to be >=2.21 which includes [this bug fix](https://sourceware.org/bugzilla/show_bug.cgi?id=17620). Users that have Ubuntu >= 16.04 or Debian >= 9 would get glibc>=2.21 by default.
