### ISSUE TITLE
mkref but get the empty "Homo_sapiens_ensembl_99.refFlat"

### ISSUE THREAD

**Issue by winni-liu** [singleron-RD/CeleScope#143]
I try to use celescope to mkref,  i download the same file and code in manual.
reference put this directory: "XX/software/CeleScope-1.10.0/database/"
in the step of "celescope rna star", i get error:

subprocess.CalledProcessError: Command 'picard -Xmx20G -XX:ParallelGCThreads=4 CollectRnaSeqMetrics I=.//B11T/03.star/B11T_Aligned.sortedByCoord.out.bam O=.//B11T/03.star/B11T_region.log REF_FLAT=XXX/software/CeleScope-1.10.0/database/Homo_sapiens_ensembl_99.refFlat STRAND=NONE VALIDATION_STRINGENCY=SILENT' returned non-zero exit status 1.

when i check the "Homo_sapiens_ensembl_99.refFlat" , and i found it's empty.

**Comment by zhouyiqi91** [comment]
`Homo_sapiens_ensembl_99.refFlat` is generated with `celescope rna mkref`. When you ran `celescope rna mkref`, did you get any error?

**Comment by winni-liu** [comment]
No error was reported，
les Log.out | head -n 20
`STAR version=2.7.9a
STAR compilation time,server,dir=2021-07-15T17:03:54+08:00 :/home/data/XXX/software/STAR-2.7.9a/source
##### Command Line:
STAR --runMode genomeGenerate --runThreadN 6 --genomeDir ./ --genomeFastaFiles Homo_sapiens.GRCh38.dna.primary_assembly.fa --sjdbGTFfile Homo_sapiens.GRCh38.99.gtf --sjdbOverhang 100
##### Initial USER parameters from Command Line:
###### All USER parameters from Command Line:
runMode                       genomeGenerate        ~RE-DEFINED
runThreadN                    6     ~RE-DEFINED
genomeDir                     ./     ~RE-DEFINED
genomeFastaFiles              Homo_sapiens.GRCh38.dna.primary_assembly.fa        ~RE-DEFINED
sjdbGTFfile                   Homo_sapiens.GRCh38.99.gtf     ~RE-DEFINED
sjdbOverhang                  100     ~RE-DEFINED
##### Finished reading parameters from all sources

##### Final user re-defined parameters-----------------:
runMode                           genomeGenerate
runThreadN                        6
genomeDir                         ./
genomeFastaFiles                  Homo_sapiens.GRCh38.dna.primary_assembly.fa
sjdbGTFfile                       Homo_sapiens.GRCh38.99.gtf`
les Log.out | tail -n 20
`Jun 20 15:27:51   Finished preparing junctions
Jun 20 15:27:51 ..... inserting junctions into the genome indices
Jun 20 15:30:02   Finished SA search: number of new junctions=383200, old junctions=0
Jun 20 15:30:46   Finished sorting SA indicesL nInd=153280000
Genome size with junctions=3215411168  3138387968   77023200
GstrandBit1=32   GstrandBit=32
Jun 20 15:31:48   Finished inserting junction indices
Jun 20 15:32:12   Finished SAi
Jun 20 15:32:12 ..... finished inserting junctions into genome
Jun 20 15:32:12 ... writing Genome to disk ...
Writing 3215411168 bytes into .//Genome ; empty space on disk = 100488540749824 bytes ... done
SA size in bytes: 24935534806
Jun 20 15:32:14 ... writing Suffix Array to disk ...
Writing 24935534806 bytes into .//SA ; empty space on disk = 100485290475520 bytes ... done
Jun 20 15:32:34 ... writing SAindex to disk
Writing 8 bytes into .//SAindex ; empty space on disk = 100458965245952 bytes ... done
Writing 120 bytes into .//SAindex ; empty space on disk = 100458965245952 bytes ... done
Writing 1565873491 bytes into .//SAindex ; empty space on disk = 100458965245952 bytes ... done
Jun 20 15:32:37 ..... finished successfully
DONE: Genome generation, EXITING`

**Comment by zhouyiqi91** [comment]
I'm referring to the stdout of the `celescope rna mkref` command, not the STAR log; the refflat file is not produced by STAR.
The refflat file is actually generated with the following command:
```
gtfToGenePred -genePredExt -allErrors -ignoreGroupsWithoutExons \
Homo_sapiens_ensembl_99.gtf /dev/stdout | \
awk '{print $12"\t"$1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9"\t"$10}' \
> Homo_sapiens_ensembl_99.refFlat \
```

Also, I noticed that the version in the STAR log file is 2.7.9a. The STAR version used by the celescope conda environment is 2.6.1b. https://github.com/singleron-RD/CeleScope/blob/master/conda_pkgs.txt. This indicates that the celescope conda environment is not properly activated.
