### ISSUE TITLE
有关中断任务之后的重新运行

### ISSUE THREAD

**Issue by ProxyLau** [singleron-RD/CeleScope#15]
您好，我在运行CeleScope软件的时候出现一些问题，想在此请教一下。
在该工具运行的时候因为各个步骤引用的有些工具对计算机硬件要求较高（尤其是内存），经常导致分析中断。再次使用工具时又要从分离barcode开始。单细胞分析的每一步都需要消耗很多的时间，不必要地消耗了时间。
是否有从中断的地方重新开始的方法呢？毕竟每一步运行完成后结果文件都已经保存在文件里了

**Comment by zhouyiqi91** [comment]
参考[多样本运行与分步运行](https://github.com/singleron-RD/CeleScope/wiki/%E5%A4%9A%E6%A0%B7%E6%9C%AC%E8%BF%90%E8%A1%8C%E4%B8%8E%E5%88%86%E6%AD%A5%E8%BF%90%E8%A1%8C)。
multi_{assay}生成的shell中包含所有的步骤, 可以从中挑选想要运行的步骤。如果只想生成某些步骤的shell, 加入`--steps_run`参数。例如：
```
multi_rna \
    --mapfile {mapfile} \
    --genomeDir {genomeDir}\
    --mod shell\
    --steps_run count,analysis
```

**Comment by ProxyLau** [comment]
谢谢，这对我很有用^_^
