### ISSUE TITLE
How to create fusion_pos file?

### ISSUE THREAD

**Issue by cx994** [singleron-RD/CeleScope#152]
I want to detect gene fusion in my single cell sample,so can I use the fusion function in the celescope?And how can I create or get the fusion_pos file when I use the `mk_ref` function in `celescope fusion`?

**Comment by zhouyiqi91** [comment]
You can get the fusion_pos file of the pre-defined blood panel at: https://github.com/singleron-RD/CeleScope/tree/dev/celescope/data/fusion/blood_1


`--fusion_pos` fusion position file. A two column tab-delimited text file with header.
"pos" is the end postion of the first gene(1-based).
e.g.  
name	pos  
PML_3	183  
PML_4	254  
PML_5	326  
PML_6	204
https://github.com/singleron-RD/CeleScope/blob/dev/docs/fusion/mkref.md
