### ISSUE TITLE
count

### ISSUE THREAD

**Issue by cool-lihf** [singleron-RD/CeleScope#16]
你好，
       我在使用celescope进行count时发现data.json没有键名为barcode_summary的行，请问data['barcode_summary']怎么获得？
      以下代码在279行左右
     json_file = outdir + '/.data.json'
     fh = open(json_file)
    data = json.load(fh)
    str_number = data['barcode_summary'][1][1].split("(")[0]

**Comment by zhouyiqi91** [comment]
在barcode步骤运行成功后就会在.data.json中生成"barcode_summary"

**Comment by cool-lihf** [comment]
您好，
        多谢您的回复，万分激动。但是我未使用celescope的barcode获取barcode，我是从STAR开始使用celescope的，我看了counts步骤后生成的文件，目前打算使用counts文件夹下的XX_counts.txt文件第一列的barcode总和作为barcode_summary，不知是否可行？

**Comment by zhouyiqi91** [comment]
1. 如果您从STAR开始使用celescope, 那么要确保输入的fastq的read name与barcode步骤生成的fastq的read name一致，这样才能正确地将read分配到barcode和UMI。
https://github.com/singleron-RD/CeleScope/wiki/barcode
> barcode和UMI包含在read name中，read name的格式为 {barcode}_{UMI}

2. barcode_summary示例：
"barcode_summary": [["Raw Reads", " 200,000"], ["Valid Reads", " 146,886(73.44%)"], ["Q30 of Barcodes", " 95.27%"], ["Q30 of UMIs", " 87.75%"]]
count步骤需要的是Valid Reads的值，即146,886

**Comment by zhouyiqi91** [comment]
您可以使用{sample}_counts.txt文件中readcount列的总和作为Valid Reads的替代。这个总和是filter后的valid reads数。

**Comment by cool-lihf** [comment]
非常感谢，我根据自己的readname修改了count.py中的部分代码，现根据您的回复已经顺利生成stat.txt文件，再次感谢您的回复。
