### ISSUE TITLE
SNP pipeline error

### ISSUE THREAD

**Issue by SingleronHH** [singleron-RD/CeleScope#176]
HI:
   I am trying the celescope_test_script on celescope_test_data using SNP pipeline. I had this error in the middle of the run:

bcftools: symbol lookup error: /opt/conda/envs/saturn/envs/celescope/bin/../lib/libgsl.so.25: undefined symbol: cblas_ctrmv

  I installed Celescope from github follow the instructions from here: https://github.com/singleron-RD/CeleScope/blob/master/docs/installation.md.

$ git clone https://github.com/singleron-RD/CeleScope.git
$ cd CeleScope
$ conda install mamba
$ mamba create -n celescope -y --file conda_pkgs.txt
$ conda activate /opt/conda/envs/saturn/envs/celescope
$ pip install celescope

  then install reference db 

celescope rna mkref \
 --thread 32 \
 --genome_name Homo_sapiens_ensembl_99 \
 --fasta Homo_sapiens.GRCh38.dna.primary_assembly.fa \
 --gtf Homo_sapiens.GRCh38.99.gtf

then install SNP db
celescope snp mkref \
 --thread 32 \
 --genome_name Homo_sapiens_ensembl_99 \
 --fasta Homo_sapiens.GRCh38.dna.primary_assembly.fa

then run the run_shell.sh under the celescope_test_script/snp/
a folder named "shell" was generated and a sh script was in it.

then I run the sh script under the "shell" dir from the  celescope_test_script/snp/ dir.

everything was fine and the GATK was finished successfully.

the error came out when the pipeline tried to use bcftools to call the variants.

2022-09-20 03:35:07,085 - celescope.tools.step.debug_subprocess_call - INFO - bcftools mpileup -f /home/jovyan/git/CeleScope/hs_ensembl_99/Homo_sapiens.GRCh38.dna.primary_assembly.fa --threads 4 --annotate DP,AD -d 100000000 -o .//test1/07.variant_calling/test1_raw.bcf .//test1/07.variant_calling/test1_splitN.bam  --regions-file /opt/conda/envs/saturn/envs/celescope/lib/python3.9/site-packages/celescope/data/snp/panel/lung_1.bed 
bcftools: symbol lookup error: /opt/conda/envs/saturn/envs/celescope/bin/../lib/libgsl.so.25: undefined symbol: cblas_ctrmv

please advise how to solve this issue.

Thanks you very much for your help!

**Comment by SingleronHH** [comment]
BTW: when I tried to run the bcftools, the error show up. It seems that the error is due to bcftools

> bcftools
bcftools: symbol lookup error: /opt/conda/envs/saturn/envs/celescope/bin/../lib/libgsl.so.25: undefined symbol: cblas_ctrmv

**Comment by SingleronHH** [comment]
BTW: 
do you have docs for maple? 
as I found in the celescope_test_script, the test1.mapfile contains 
snp     ../../celescope_test_data/snp/fastqs    test1   ../../celescope_test_data/snp/snp_match_dir

I can understand snp part, but what is the rest "test1   ../../celescope_test_data/snp/snp_match_dir"?

thank you very much for your help!

**Comment by zhouyiqi91** [comment]
Similar issue here: https://github.com/bcbio/bcbio-nextgen/issues/3632

> BTW: when I tried to run the bcftools, the error show up. It seems that the error is due to bcftools
> 
> > bcftools
> > bcftools: symbol lookup error: /opt/conda/envs/saturn/envs/celescope/bin/../lib/libgsl.so.25: undefined symbol: cblas_ctrmv

**Comment by zhouyiqi91** [comment]
> BTW: do you have docs for maple? as I found in the celescope_test_script, the test1.mapfile contains snp ../../celescope_test_data/snp/fastqs test1 ../../celescope_test_data/snp/snp_match_dir
> 
> I can understand snp part, but what is the rest "test1 ../../celescope_test_data/snp/snp_match_dir"?
> 
> thank you very much for your help!

https://github.com/singleron-RD/CeleScope/blob/master/docs/snp/multi_snp.md#arguments
4th column: The 4th column has different meaning for each assay. The single cell rna directory after running CeleScope is called `matched_dir`
