### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/SGRNJ06/randd/USER/zhouyiqi/test/gtf_filter/celescope_genome.config'

### ISSUE THREAD

**Issue by AcetylCoALab** [singleron-RD/CeleScope#183]
An error is reported when running the test data, FileNotFoundError: [Errno 2] No such file or directory: '/SGRNJ06/randd/USER/zhouyiqi/test/gtf_filter/celescope_genome.config'
, the hs_ensembl_99 path has also been set when running personal data, but it still prompts that genomeDir is not set
 help!!!!!

**Comment by zhouyiqi91** [comment]
https://github.com/singleron-RD/celescope_test_script/blob/master/rna/run_shell.sh

Have you changed `--genomeDir` to the path to ensembl_99 on your server?

**Comment by AcetylCoALab** [comment]
I didn't change any paths and ran pytest directly according to the official method, python -m pytest -s test_multi.py --assays rna. Is this what is the reason
