### ISSUE TITLE
How to update CeleScope?

### ISSUE THREAD

**Issue by asdChenJin** [singleron-RD/CeleScope#189]
How to update celescope version to the latest version？
Do I need to re-clone the Git repository for each update, then create the environment and install the software?
I hope you can clarify this.Thank you very much.

**Comment by zhouyiqi91** [comment]
Use pip install to update the celescope version, for example from celescope1.12.0 to 1.13.0 (assuming you installed 1.12.0 in a conda environment named celescope)
```
conda activate celescope
pip install celescope==1.13.0
```

But `pip install` can only update python packages. It cannot update packages that depend on conda. If the two versions of conda_pkgs are different, you need to create a new conda environment. For example, to upgrade from 1.5.0 to 1.13.0, it is required to create a new conda environment.
https://github.com/singleron-RD/CeleScope/blob/v1.5.0/conda_pkgs.txt
https://github.com/singleron-RD/CeleScope/blob/v1.13.0/conda_pkgs.txt
