### ISSUE TITLE
Where is fusion_genomeDir？

### ISSUE THREAD

**Issue by asdChenJin** [singleron-RD/CeleScope#194]
Hello, I want to use fusion pipeline, but I can't find the path of `--fusion_genomeDir` in multi_fusion(run_shell.sh). How can I get it? Thank you very much!

**Comment by zhouyiqi91** [comment]
https://github.com/singleron-RD/CeleScope/tree/master/celescope/data/fusion/blood_1

**Comment by asdwyf** [comment]
> 

I find it, I mean that how to download it in Linux, use wget will download HTML file, not fasta file. Now, I use copy and paste to complete three files. Is there a more convenient way. Thanks.

**Comment by asdwyf** [comment]
> https://github.com/singleron-RD/CeleScope/tree/master/celescope/data/fusion/blood_1
I find it, I mean that how to download it in Linux, use wget will download HTML file, not fasta file. Now, I use copy and paste to complete three files. Is there a more convenient way. Thanks.

**Comment by asdChenJin** [comment]
> https://github.com/singleron-RD/CeleScope/tree/master/celescope/data/fusion/blood_1

I find it, I mean that how to download it in Linux, use wget will download HTML file, not fasta file. Now, I use copy and paste to complete three files. Is there a more convenient way. Thanks.

**Comment by zhouyiqi91** [comment]
```
git clone https://github.com/singleron-RD/CeleScope.git
ls celescope/data/fusion/blood_1/
```

**Comment by asdChenJin** [comment]
> ```
> git clone https://github.com/singleron-RD/CeleScope.git
> ls celescope/data/fusion/blood_1/
> ```

Thank you very much!
