### ISSUE TITLE
threads for multi_rna

### ISSUE THREAD

**Issue by univerchen** [singleron-RD/CeleScope#197]
Hello, while generating scripts for each sample with multi_rna, why the maximum thread should not exceed 20?

"--thread    Threads to use. The recommended setting is 8, and the maximum should not exceed 20."

Thank you.

**Comment by zhouyiqi91** [comment]
https://github.com/alexdobin/STAR/issues/430
> mapping speed saturates at >~20 threads

https://www.biorxiv.org/content/10.1101/2021.05.05.442755v1.full
> We see that for most tools the processing speed saturates at ~16-20 threads

https://www.biostars.org/p/259856/
> Alignment requires a certain additional amount of memory per thread; it's possible that with 16 threads you didn't swap but with 32 threads you do.
