### ISSUE TITLE
cell calling

### ISSUE THREAD

**Issue by univerchen** [singleron-RD/CeleScope#200]
Hello, in the rna pipeline(v1.13), performing featurecounts at the gene level or exon level would lead to different cell numbers. With my data, the gene level gave about 6900 cells, while the exon level gave about 8100 cells. What's causing this difference? 
Thank you.

**Comment by zhouyiqi91** [comment]
When performing featurecounts at `gene` level, reads mapped to introns will be included.
Normally, this will increase the number of UMIs assigned to each barcode, and more barcodes will be considered as cells in the cell-calling algorithm. Therefore, the number of cells will be greater than the number of cells at the `exon` level.
Can you confirm that the `gene` level gave 6900 cells and the `exon` level gave 8100 cells?

**Comment by univerchen** [comment]
Yes, It's strange.
The median UMI and genes per cell are higher at the gene level. The estimated number of cells at gene level is 6902, while it's 8157 at exon level.
In addition, mapping to mm10 or mm39 with paired genome and annotation files also gave different cell numbers, roughly 450. Is this normal?

**Comment by zhouyiqi91** [comment]
Would you please send the HTML reports(exon and gene) to me?
zhouyiqi@singleronbio.com

**Comment by univerchen** [comment]
Sure. Thank you.
