### ISSUE TITLE
"FileNotFoundError: --match_dir or --matrix_dir is required" when running "celescope vdj count_vdj"

### ISSUE THREAD

**Issue by m-fayer** [singleron-RD/CeleScope#208]
Hi,

I created a script "bcr.sh" by command "multi_vdj --ref_path /xxx/Singleron/db/vdj/human_IG --species human --gzip --type BCR --mapfile bcr.dsp.mapfile --thread 10 --mod shell".

The last step of the script is “celescope vdj count_vdj". When running this step, an error occurred:

<pre>
Args: Namespace(subparser_assay='vdj', type='BCR', UMI_min=3, BCR_iUMI=2, TCR_iUMI=1, expected_target_cell_num=3000, target_cell_barcode=None, target_weight=3.0, UMI_count_filter_file='.//bcr/04.mapping_vdj/bcr_UMI_count_filtered.tsv', match_dir='None', matrix_dir=None, outdir='.//bcr/05.count_vdj', sample='bcr', thread='10', debug=False, func=<function count_vdj at 0x7f5a68c61550>)
Traceback (most recent call last):
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/celescope.py", line 44, in main
    args.func(args)
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/vdj/count_vdj.py", line 318, in count_vdj
    with Count_vdj(args, display_title="Count") as runner:
  File "/mnt/sata/mao/za/bcr.tcr/Singleron/celeScope3/lib/python3.9/site-packages/celescope/vdj/count_vdj.py", line 85, in __init__
    raise FileNotFoundError("--match_dir or --matrix_dir is required.")
<b>FileNotFoundError: --match_dir or --matrix_dir is required.</b>
</pre>

In the [link](https://github.com/singleron-RD/CeleScope/blob/master/docs/vdj/count_vdj.md), the missing options are match scRNA. What if we don't have such info?

I attached full screen output of the script and the script itself (slightly modified for more useful screen output) for your convenience. Feel free to let me know if further info needed.

[screen.output.txt](https://github.com/singleron-RD/CeleScope/files/10192936/screen.output.txt)

[bcr.sh.txt](https://github.com/singleron-RD/CeleScope/files/10192948/bcr.sh.txt)

**Comment by zhouyiqi91** [comment]
You need to fill the 4th column in the mapfile with `matched_dir` and regenerate the shell script. Then the `--match_dir` argument will appear in the `count_vdj` step.
```
celescope vdj count_vdj  --match_dir ../../celescope_test_data/vdj/fake_match_dir ...
```


https://github.com/singleron-RD/CeleScope/blob/master/docs/vdj/multi_vdj.md#arguments
4th column: The 4th column has different meaning for each assay. The single cell rna directory after running CeleScope is called matched_dir.
- `vdj` Required, matched_dir.

**Comment by m-fayer** [comment]
It worked.. Thanks!
