### ISSUE TITLE
get the 16-length cell barcode like 10X

### ISSUE THREAD

**Issue by RyanYip-Kat** [singleron-RD/CeleScope#21]
Then the matrix after the count, can I get a 16-length cell barcode like 10X?

**Comment by zhouyiqi91** [comment]
Yes, You can. But if you use GEXSCOPE single cell products, the cell barcode is 8 * 3 = 24bp.

https://github.com/singleron-RD/CeleScope/blob/master/docs/tools/count.md
> `{sample}_matrix_10X` The expression matrix of the barcode that is identified to be the cell. Can be read in by calling the `Seurat::Read10X` function.

**Comment by RyanYip-Kat** [comment]
Whether can I get 24bp 
 Cell barcode's whitelist file, similar to 10X's 3M-february-2018 .txt file

**Comment by zhouyiqi91** [comment]
https://github.com/singleron-RD/CeleScope/blob/master/celescope/data/chemistry/scopeV2.2.1/bclist

This file is the whitelist of 8bp barcodes. To get the 24bp whitelist, you can use the following python script:

```
import itertools

bcs_8 = [bc.strip() for bc in open("celescope/data/chemistry/scopeV2.2.1/bclist")]
bcs_24 = ["".join(bcs) for bcs in itertools.product(bcs_8, repeat=3)]
```

**Comment by RyanYip-Kat** [comment]
Thanks!I got it.
and I want to ask you,whether celescope fastq file can be used for indrops pipeline?(https://github.com/indrops/indrops)

**Comment by zhouyiqi91** [comment]
I don't think you can use indrops pipeline to analyze data from Singleron as the read patterns are quite different.
