### ISSUE TITLE
flv_CR mapping prompt `rds file and type file do not exist` error

### ISSUE THREAD

**Issue by asdChenJin** [singleron-RD/CeleScope#211]
Hi，this is an error when run flv_CR mapping： `Args: Namespace(subparser_assay='flv_CR', seqtype='TCR', outdir='.//B3190/06.mapping', sample='B3190', thread='32', debug=False, match_dir='/mnt/sdd/singleron_training_class/resources/support_project/LBFC20201603_22_11_15/pbmc_A01039/221103_A01040_0319_AHFNKJDSX5/script/rna/shell/B3190/', match_out='.//B3190/05.match', func=<function mapping at 0x7f40c62cbb80>)
rds file and type file do not exist`
How can I solve this problem?
Do I need to convert the h5ad files in the transcriptome 06.analysis folder to rds files?
Thanks!

**Comment by Chenjunjie1996** [comment]
This message is a just a tip, not error. if rds file exists, the mapping step will output some plots from R-Seurat library.
Whether the file exists or not, you can run flv_CR successfully .

**Comment by asdChenJin** [comment]
> This message is a just a tip, not error. if rds file exists, the mapping step will output some plots from R-Seurat library. Whether the file exists or not, you can run flv_CR successfully .

But I run this code: `celescope flv_CR mapping --outdir .//B3190/06.mapping --sample B3190 --thread 32 --seqtype TCR  --match_dir /mnt/sdd/singleron_training_class/resources/support_project/LBFC20201603_22_11_15/pbmc_A01039/221103_A01040_0319_AHFNKJDSX5/script/rna/shell/B3190/ --match_out .//B3190/05.match`, 
It prompts : `Args: Namespace(subparser_assay='flv_CR', seqtype='TCR', outdir='.//B3190/06.mapping', sample='B3190', thread='32', debug=False, match_dir='/mnt/sdd/singleron_training_class/resources/support_project/LBFC20201603_22_11_15/pbmc_A01039/221103_A01040_0319_AHFNKJDSX5/script/rna/shell/B3190/', match_out='.//B3190/05.match', func=<function mapping at 0x7fc9e274eb80>)
rds file and type file do not exist`.
And, the `06.mapping` folder is empty.
How can i run celescope flv_CR mapping?
Thanks.

**Comment by Chenjunjie1996** [comment]
You don't need to run this step. It does not affect the final result. If the rds file does not exist, the whole workflow will pass this step.
if the log file contains no error messages and 05.match directory is not empty. it means you have successfully run.

**Comment by asdChenJin** [comment]
> You don't need to run this step. It does not affect the final result. If the rds file does not exist, the whole workflow will pass this step. if the log file contains no error messages and 05.match directory is not empty. it means you have successfully run.

I get it，thanks.
