### ISSUE TITLE
test data run ERROR: genomeParameters.txt not found

### ISSUE THREAD

**Issue by jdekanter** [singleron-RD/CeleScope#214]
Hi all!

I'm testing the pipeline. The Celescope installation was successful and the generation of the genomeDir (human) also seemed successful (at least I got no errors). I have the following files in that directory (/hpc/pmc_vanboxtel/resources/celescope_human_38.99/):

```
celescope_genome.config  chrNameLength.txt  chrStart.txt                         Homo_sapiens.GRCh38.99.gtf                   Log.out
chrLength.txt            chrName.txt        Homo_sapiens.GRCh38.99.filtered.gtf  Homo_sapiens.GRCh38.dna.primary_assembly.fa
```
I have downloaded the test data and wanted to test the "rna" only for now. I've changed the genomeDir parameter in the rna/run_shell.sh script. 
I run the test by `python -m pytest -s test_multi.py --assays rna`
However it gives an error (see below) that the genomeParameters.txt file was not found. Indeed it was not generated, but I have no clue what it is or what it should contain. I've seen another user open an issue about this, but that was closed before it was answered. 
Can you help me out? Thanks in advance.

The output when running was the following:

```
rootdir: /hpc/pmc_vanboxtel/personal/jdekanter/test_celescope/celescope_test_script
collected 1 item                                                                                                                                                                         

test_multi.py 2022-12-15 13:29:34,072 - test_multi.test_mutiple - INFO - start...
log files are in: /hpc/pmc_vanboxtel/personal/jdekanter/test_celescope/celescope_test_script/log
assays to run:  ['rna']
********************running rna********************
Done           00:00:00        74,870 reads @  13.3 µs/read;   4.50 M reads/minute

EXITING because of FATAL ERROR: could not open genome file /hpc/pmc_vanboxtel/resources/celescope_human_38.99//genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions
```

**Comment by asdChenJin** [comment]
Your reference genome directory may be missing some files, here is the reference genome directory I built: 
```bash
celescope_genome.config  chrNameLength.txt  chrStart.txt  genomeParameters.txt  mkref.sh   SA
chrLength.txt            chrName.txt        Genome        Log.out               nohup.out  SAindex

**Comment by zhouyiqi91** [comment]
https://github.com/alexdobin/STAR/issues/569

**Comment by jdekanter** [comment]
Thanks! I've rerun the script with additional RAM and cores and now it completed. Although STAR specifies it, maybe it would be good to post the RAM/cores requirement for mkref on the docs here as well? I think this would also be convinient for other (main) functions, e.g. multi_{assay}.
