### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by 33Dr** [singleron-RD/CeleScope#221]
Dear all, 

I have following issue running celescope convert10X multi_convert10X.md on raw fastq files:

FileNotFoundError: [Errno 2] No such file or directory: './/test1/03.cellranger/stat.txt'

convert10X interrupts at this point without successfull results.

Maybe you could help me.
Thanks in advance,

Best

**Comment by Chenjunjie1996** [comment]
Could you please show me shell script and results in 02.convert directory?

**Comment by 33Dr** [comment]
Hi CHenjunjie1996,,
thanks for your kind reply.

multi_convert10X \
 --mapfile ./rna.mapfile \
 --chemistry flv_rna \
 --thread 8 \
 --mod shell \
 --soft_path home/path/CeleScope/cellranger

celescope convert10X sample --outdir .//test1/00.sample --sample test1 --thread 8 --chemistry flv_rna  --fq1 /home/path/CeleScope/mymapfiles/rna_1.fastq.gz 
celescope convert10X barcode --outdir .//test1/01.barcode --sample test1 --thread 8 --chemistry flv_rna --lowNum 2  --fq1 /home/path/CeleScope/mymapfiles/rna_1.fastq.gz --fq2 /home/path/CeleScope/mymapfiles/rna_2.fastq.gz 
celescope convert10X convert --outdir .//test1/02.convert --sample test1 --thread 8 --soft_path home/path/CeleScope/cellranger --tenX_chemistry V2  --fq2 .//test1/01.barcode/test1_2.fq 
celescope convert10X cellranger --outdir .//test1/03.cellranger --sample test1 --thread 8 --soft_path home/path/CeleScope/cellranger --mem 10  --fqs_dir .//test1/02.convert 

Convert directory folder is empty

Best!

**Comment by Chenjunjie1996** [comment]
You can try following script:
multi_convert10X  --chemistry flv_rna --mapfile ./rna.mapfile --thread 8 --soft_path "/soft/cellranger/cellranger-6.1.2/cellranger"  --ref_path "/soft/cellranger/refdata-gex-GRCh38-2020-A"
- Specifying the soft_path and ref_path manually.  soft_path and ref_path require absolute path of cellranger program and 
and reference data files. Download pages: https://support.10xgenomics.com/single-cell-gene-expression/software/downloads/latest
- Chemistry can be detected automatically in latest celescope version.  If you have installed latest celescope version, you can ignore "--chemistry" parameter

**Comment by 33Dr** [comment]
Thanks Chenjunjie1996,

I will try following your advices.
Best

**Comment by 33Dr** [comment]
What exactly is --soft_path: soft path for cellranger and --ref_path reference path for cellranger?

**Comment by Chenjunjie1996** [comment]
You can refer to step1 ans step 2 of https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/installation
Soft path and reference path are absolute path of  cellranger and reference data files after unpacking.
For example:
- ![image](https://user-images.githubusercontent.com/74704889/217979565-a07c8586-506b-430a-8b86-33580f413054.png)
--soft_path "/SGRNJ03/randd/cjj/soft/cellranger/cellranger-6.1.2/cellranger"

- ![image](https://user-images.githubusercontent.com/74704889/217979622-b5d242b0-10ce-4b50-b224-cea0240720f8.png)
--ref_path "/SGRNJ03/randd/cjj/soft/cellranger/refdata-gex-GRCh38-2020-A"

**Comment by 33Dr** [comment]
Thank you very much, Chenjunjie1996, it worked now.
Best

**Comment by 33Dr** [comment]
Dear all,

to run multi convert 10X itself worked very well. 

But I have another problem now. I tried to convert the fastq files which derive from GEXSCOPE to the 10X format running multi convert 10x. When I compare the scopeV2.2.1 output with the Cellranger output after running multi convert 10X, I can observe huge differences in Mean Reads per Cell, Total Genes and Median Genes per Cell. 

Could you please help me?
Thanks in advance,

Best

**Comment by Chenjunjie1996** [comment]
Could you please send the celescope and cellranger HTML reports to me?
chenjunjie@singleronbio.com

**Comment by 33Dr** [comment]
Thanks for your help, Chenjunjie. I sent it to you.
Best

**Comment by 33Dr** [comment]
I used the following script:

multi_convert10X --chemistry flv_rna --mapfile ./rna.mapfile --thread 8 --mod shell --soft_path "/home/opt/cellranger-7.1.0/cellranger" --ref_path "/home/opt/cellranger-7.1.0/refdata-gex-GRCh38-2020-A"

**Comment by Chenjunjie1996** [comment]
multi_convert10X  --mapfile ./rna.mapfile --thread 8 --mod shell --soft_path "/home/opt/cellranger-7.1.0/cellranger" --ref_path "/home/opt/cellranger-7.1.0/refdata-gex-GRCh38-2020-A"

**Comment by 33Dr** [comment]
Thank you so much for your help and support. It worked!
