### ISSUE TITLE
[W::bgzf_read_block] EOF marker is absent. The input may be truncated.

### ISSUE THREAD

**Issue by univerchen** [singleron-RD/CeleScope#223]
Hello, while running the rna pipeline, in the log file of the barcode step, 

2023-02-11 11:20:00,391 - celescope.tools.barcode.get_mismatch_dict - INFO - start...
2023-02-11 11:20:00,402 - celescope.tools.barcode.get_mismatch_dict - INFO - done. time used: 0:00:00.010138
2023-02-11 11:20:00,403 - celescope.tools.barcode.get_mismatch_dict - INFO - start...
2023-02-11 11:20:00,439 - celescope.tools.barcode.get_mismatch_dict - INFO - done. time used: 0:00:00.036029
[W::bgzf_read_block] EOF marker is absent. The input may be truncated
[W::bgzf_read_block] EOF marker is absent. The input may be truncated

The pipeline finished successfully. Do these warnings mean the input fastq files are truncated?

Thank you.

**Comment by zhouyiqi91** [comment]
If the pipeline finished successfully, the input fastq files are NOT truncated and you can just ignore the warning. The warnings come from a issue with pysam.

**Comment by jingydz** [comment]
I've encountered a similar issue, but it's likely not related to pysam since running other VCF files doesn't present this problem. Are there any other solutions to this issue?

**Comment by jingydz** [comment]
[main_vcfview] Error: cannot write to xxx.sample..vcf.gz
[E::bgzf_read_block] Failed to read BGZF block data at offset 23298260 expected 11071 bytes; hread returned 3866
[W::bgzf_read_block] EOF marker is absent. The input is probably truncated
