### ISSUE TITLE
New version of celescope, old version of singleron scRNA-seq data

### ISSUE THREAD

**Issue by yemao701** [singleron-RD/CeleScope#242]
We have encountered an issue with the new version of celescope when analyzing our singleron scRNA-seq data. After sequencing three batches of data, we observed that version 1.15 of celescope improves valid reads and mean gene per cell (--chemistry auto) compared to version 1.10. However, we found that this improvement only applies to batch2 and batch3 of our recently released data. When analyzing batch1 data (released in Oct. 2022) using version 1.15, we generated fewer cells (730 cells versus 19432 cells) and observed ambiguous cell clusters compared to using version 1.10, even after changing the parameters (--chemistry scopeV1). We are seeking guidance on how we can use version 1.15 to analyze our older batch of singleron scRNA-seq data.

**Comment by zhouyiqi91** [comment]
Would you please send the HTML reports(1.10 and 1.15) of batch1 to zhouyiqi@singleronbio.com?
