### ISSUE TITLE
Chemistry Error with "Auto" parameter.

### ISSUE THREAD

**Issue by hkarakurt8742** [singleron-RD/CeleScope#251]
Hello,
I am trying to use CeleScope on a public dataset (GSE180286) that prepared using Singleron GENXSCOPE but I have some questions since it is my first time analyzing a Singleron Biotechnologies based dataset. 
First, when I use "auto" for chemistry parameter I have an error. When I change it to "scopeV1" it looks like it is working (still running, I just started) and I have no idea about the chemistry (I contacted the researchers but do not have any reply yet). What might be the reason of "auto" parameter error? As I know scopeV1 is no longer in use (as CellScope gave the information).
Second, is GENXSCOPE a full-length transcript platform similar to Smart-Seq2 or it sequences only a part of 3'-end similar to other UMI-based platforms such as 10X.
Sorry for my simple questions, I just started using the Singleron based data.

My CeleScope version: 1.16.2

Thank you in advance.

**Comment by zhouyiqi91** [comment]
1. GSE180286 is scopeV1.
2. GENXSCOPE is a 3ʹ kit silimar to 10X.

**Comment by hkarakurt8742** [comment]
> 1. GSE180286 is scopeV1.
> 2. GENXSCOPE is a 3ʹ kit silimar to 10X.

Thank you so much.
