### ISSUE TITLE
Lung panel gene list - KRAS

### ISSUE THREAD

**Issue by WouterMidden** [singleron-RD/CeleScope#264]
Hi,
There is a wrong gene name in the lung panel gene list (KARS instead of KRAS). The KRAS gene does not show up (either WT or MT) in our html.report for the enriched library. We don't expect to have a mutation in KRAS, but might the wrong name be responsible for not appearing in the list?
https://github.com/singleron-RD/CeleScope/blob/caae6194127b857559fbeed4c1033b91168c27bb/celescope/data/snp/panel/lung_1.bed#L13

And to be on the safe side with interpreting the data: 0/0 = WT, 0/1 = both WT and MT reads, 1/1 = MT?

Thanks!

**Comment by zhouyiqi91** [comment]
1. The wrong name is responsible for the absense of KRAS in the final result. Thank you for reporting.

2. You are right on the genotype
- 0/0 : the sample is homozygous reference
- 0/1 : the sample is heterozygous, carrying 1 copy of each of the REF and ALT alleles
- 1/1 : the sample is homozygous alternate
