### ISSUE TITLE
No bclist found for chemistry scopeV1 under

### ISSUE THREAD

**Issue by guijie2015** [singleron-RD/CeleScope#270]
I am analyzing the public data which is using scopeV1, but I could not find any scopeV1 data in your github anymore . Can you send the scopeV1 to my email(1290560722@qq.com)? Thank you very much!

**Comment by zhouyiqi91** [comment]
scopeV1 is like Drop-Seq which does not have barcode whitelist. The barcodes in this method are randomly generated barcodes of 12 bp.
You can use the lastest CeleScope version v2.0.6 and specify `--chemistry scopeV1` to analyze the data.

**Comment by guijie2015** [comment]
Very thanksful! It is work for me
