### ISSUE TITLE
Splitting VDJ fails

### ISSUE THREAD

**Issue by MarcElvld** [singleron-RD/CeleScope#274]
**Describe the bug**
Splitting the VDJ of a multiplexed sample fails. 

celescope tag split_tag --outdir .//LMI_S001_HTO_v2/05.split_tag --sample LMI_S001_HTO_v2 --thread 4 --split_vdj --vdj_dir /mnt/home/marce/Analyses/LMI_S001_TCR_v2 --split_matrix --match_dir /mnt/home2/marce/Analyses/LMI_S001_cDNA_v2 --umi_tag_file .//LMI_S001_HTO_v2/03.count_tag/LMI_S001_HTO_v2_umi_tag.tsv 

Splitting the expression matrix works fine (when --split_vdj --vdj_dir /mnt/home/marce/Analyses/LMI_S001_TCR_v2 is removed from the line)

Splitting VDJ gives an error:
Traceback (most recent call last):
  File "/home/marce/anaconda3/envs/celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/home/marce/anaconda3/envs/celescope/lib/python3.9/site-packages/celescope/celescope.py", line 54, in main
    args.func(args)
  File "/home/marce/anaconda3/envs/celescope/lib/python3.9/site-packages/celescope/tag/split_tag.py", line 246, in split_tag
    with Split_tag(args) as runner:
  File "/home/marce/anaconda3/envs/celescope/lib/python3.9/site-packages/celescope/tag/split_tag.py", line 98, in __init__
    self.cell_confident_vdj = glob.glob(f'{args.vdj_dir}/*count_vdj/*cell_confident.tsv*')[0]
IndexError: list index out of range

Celescope version 2.0.6

**Comment by Chenjunjie1996** [comment]
Can you check if the cell confident vdj file exists?
```
/mnt/home/marce/Analyses/LMI_S001_TCR_v2/*count_vdj/*cell_confident.tsv
```

**Comment by MarcElvld** [comment]
The file exists. I added it to the mail.

From: Chenjunjie1996 ***@***.***>
Date: Wednesday, 28 February 2024 at 11:18
To: singleron-RD/CeleScope ***@***.***>
Cc: Eleveld, Marc ***@***.***>, Author ***@***.***>
Subject: Re: [singleron-RD/CeleScope] Splitting VDJ fails (Issue #274)
U ontvangt niet vaak e-mail van ***@***.*** Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Can you check if the cell confident vdj file exists?

/mnt/home/marce/Analyses/LMI_S001_TCR_v2/*count_vdj/*cell_confident.tsv

**Comment by MarcElvld** [comment]
Ok, retried by making new shell files and now it works again. Looks like the was a mistake in a folder reference. It works again. Thank you for your help.
