### ISSUE TITLE
celescope rna mkref but no folder output

### ISSUE THREAD

**Issue by CaiCheng1996** [singleron-RD/CeleScope#280]
**Describe the bug**
Run mkref to make my own index:
celescope rna mkref --genome_name Sugarglider_Genome --fasta sugarglider.fasta --gtf sugarglider.gtf --thread 12

A lot of outpu files but no folder named "Sugarglider_Genome" that I want like cellranger.
Output includes:(Too many useless files, it's really terrible)
celescope_genome.config
chrLength.txt
chrNameLength.txt
chrName.txt
chrStart.txt
exonGeTrInfo.tab
exonInfo.tab
geneInfo.tab
Genome
genomeParameters.txt
Log.out
SA
SAindex
sjdbInfo.txt
sjdbList.fromGTF.out.tab
sjdbList.out.tab
transcriptInfo.tab

**Comment by Chenjunjie1996** [comment]
You can manually create Sugarglider_Genome folder.
1. mkdir Sugarglider_Genome
2. cd Sugarglider_Genome
3. celescope rna mkref --genome_name Sugarglider_Genome --fasta sugarglider.fasta --gtf sugarglider.gtf --thread 12

**Comment by zhouyiqi91** [comment]
The mkref command generates the genome index file in the current directory. You can rename the directory where you run the mkref command to `Sugarglider_Genome` and then provide the path to this directory to the `--genomeDir` parameter when running the rna pipeline.
