### ISSUE TITLE
SNP calling

### ISSUE THREAD

**Issue by Zymaniswenzai** [singleron-RD/CeleScope#30]
Hi, Celescope team!

I got .bam file by following your tutorial. and I used bcftools to generate vcf file :
`bcftools mpileup -Ou -f Homo_sapiens.GRCh38.dna.primary_assembly.fa A1_Aligned.sortedByCoord.out.bam | bcftools call -Ou -mv | bcftools filter -s LowQual -e '%QUAL<20 || DP>100' > A1.flt.vcf
`

The header of vcf file looks like this:
`#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  A1_Aligned.sortedByCoord.out.bam`

and I generated .ped and .map files.

the map file looks like this:
![9871624350932_ pic_hd](https://user-images.githubusercontent.com/30076901/122892435-f7639680-d377-11eb-917f-e3d01b475728.jpg)
I know the rsid of SNP can be annotated.

but the ped file is strange:
![image](https://user-images.githubusercontent.com/30076901/122892679-2da11600-d378-11eb-9c96-d4543f525efb.png)

It looks like the result of a whole sample. How can I get the SNP result including each cell? eg. the result files contains cell UMI barcodes so I can recognize which variants come from which cells?

Thanks for any helps!!

Jingwen

**Comment by zhouyiqi91** [comment]
1. Are you going to call variants on single cell RNA-Seq Data? It is not recommended because usually the coverage is not sufficient.
2. CeleScope does include a variant calling pipeline for target sequencing. However,  this pipeline is not well documented as it is not released.

**Comment by Zymaniswenzai** [comment]
@zhouyiqi91 Yes, our samples were sequenced by Singleron company. How can I get the variant calling pipeline?

**Comment by zhouyiqi91** [comment]
The pipeline has been included in Celescope but not well documented. 

The variant calling pipeline is for single cell target sequencing but can be used for scRNA-Seq data. 
- If you don't need annovar annotation, ignore --annovar_config.
- You need to add gatk 4.0 to you conda env.
```

multi_snp\
 --mapfile ./test1.mapfile\
 --genomeDir {genomeDir after running celescope snp mkref}\
 --thread 10\
 --mod shell\
 --gene_list gene_list.tsv\
 --annovar_config annovar.config\
 --not_consensus
```

annovar_config
```
[ANNOVAR]
dir = /Public/Software/annovar/
db = /SGRNJ/Database/script/database/annovar/humandb
buildver = hg38
protocol = refGene,cosmic70
operation = g,f
```

Relevant Docs
https://github.com/singleron-RD/CeleScope/blob/master/docs/snp/

**Comment by Zymaniswenzai** [comment]
@zhouyiqi91 Thanks for your reply! 
How does Celescope  snp build the reference? and which annotation file should I download when building the reference？

In this command line: --gene_list gene_list.tsv , Is this .tsv file an output file or an input file?

Thanks very much for your help!

Jingwen

**Comment by zhouyiqi91** [comment]
1. https://github.com/singleron-RD/CeleScope/blob/dev/docs/snp/mkref.md 
If you have run `celescope rna mkref`, you do not need to download additional files.

2. https://github.com/singleron-RD/CeleScope/blob/dev/docs/snp/multi_snp.md
It is an input file.
`--gene_list` Required. Gene list file, one gene symbol per line. Only results of these genes are reported.

**Comment by Zymaniswenzai** [comment]
@zhouyiqi91 Should I re-install celescope again? Since  I found that the version I installed earlier did not have `celescope snp mkref` in it.
![image](https://user-images.githubusercontent.com/30076901/123722840-b7426d80-d8bb-11eb-8e3d-3bb88e2f9a51.png)
the files in the `CeleScope/celescope/celescope/snp`
![image](https://user-images.githubusercontent.com/30076901/123722903-d6d99600-d8bb-11eb-80e7-8eb2983989bb.png)

and I need to re-run `celescope rna mkref`, rihgt?
Thanks!

**Comment by zhouyiqi91** [comment]
1. You should upgrade celescope to the lastest version. `celescope snp mkref` has been added since version 1.3.0.
2. If you have run `celescope rna mkref` before, **NO** need to re-run it. Just run `celescope snp mkref`.

**Comment by Zymaniswenzai** [comment]
I followed the tutorial :
`Install conda packages`
`cd CeleScope`
`conda create -n celescope`
`conda activate celescope`
`conda install --file conda_pkgs.txt --channel conda-forge --channel bioconda --channel r --channel imperial-college-research-computing
`

and I used to install software in a specific folder. so I ran this commande line `git clone https://gitee.com/singleron-rd/celescope.git` under this folder`/home/lailab/software/`. also, I downloaded the reference genome files and put them in this folder `/home/lailab/software/celescope/celescope/hs/ensembl_99`

The ‘celescope’ environment created by conda is in this folder `/home/lailab/miniconda3/envs/celescope`. 

Although I had successfully built the rna reference and completed the scRNA analysis before. When I tried to build snp reference genome. The log file is recorded as follows：

`2021-06-30 11:22:09,033 - celescope.snp.mkref.run - INFO - start...
Traceback (most recent call last):
  File "/home/lailab/miniconda3/envs/celescope/bin/celescope", line 8, in <module>
    sys.exit(main())
  File "/home/lailab/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/celescope.py", line 37, in main
    args.func(args)
  File "/home/lailab/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/snp/mkref.py", line 62, in mkref
    runner.run()
  File "/home/lailab/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/utils.py", line 50, in wrapper
    result = func(*args, **kwargs)
  File "/home/lailab/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/snp/mkref.py", line 50, in run
    f"{self.config_file} not exist! "
AssertionError: .//celescope_genome.config not exist! You need to build rna genome with 'celescope rna mkref' first.`


And the log file about rna mkref  is recorded as follows：

```
2021-06-29 15:58:02,795 - celescope.rna.mkref.run - INFO - start...
2021-06-29 15:58:02,795 - celescope.rna.mkref.build_refflat - INFO - start...
2021-06-29 15:58:02,795 - celescope.rna.mkref.build_refflat - INFO - gtfToGenePred -genePredExt -geneNameAsName2 \
/home/lailab/software/celeScope/celescope/celescope/hs/ensembl_99/Homo_sapiens.GRCh38.99.gtf /dev/stdout | \
awk '{print $12"\t"$1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7"\t"$8"\t"$9"\t"$10}' \
> Homo_sapiens_ensembl_99.refFlat \

2021-06-29 15:58:23,255 - celescope.rna.mkref.build_refflat - INFO - done. time used: 0:00:20.460496
2021-06-29 15:58:23,257 - celescope.rna.mkref.build_star_index - INFO - start...
2021-06-29 15:58:23,257 - celescope.rna.mkref.build_star_index - INFO - STAR \
--runMode genomeGenerate \
--runThreadN 6 \
--genomeDir ./ \
--genomeFastaFiles /home/lailab/software/celeScope/celescope/celescope/hs/ensembl_99/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
--sjdbGTFfile /home/lailab/software/celeScope/celescope/celescope/hs/ensembl_99/Homo_sapiens.GRCh38.99.gtf \
--sjdbOverhang 100 \

Jun 29 15:58:23 ..... started STAR run
Jun 29 15:58:23 ... starting to generate Genome files
Jun 29 15:59:50 ... starting to sort Suffix Array. This may take a long time...
Jun 29 16:00:16 ... sorting Suffix Array chunks and saving them to disk...
Jun 29 17:11:08 ... loading chunks from disk, packing SA...
Jun 29 17:14:02 ... finished generating suffix array
Jun 29 17:14:02 ... generating Suffix Array index
Jun 29 17:18:48 ... completed Suffix Array index
Jun 29 17:18:48 ..... processing annotations GTF
Jun 29 17:19:20 ..... inserting junctions into the genome indices
Jun 29 17:25:22 ... writing Genome to disk ...
Jun 29 17:25:25 ... writing Suffix Array to disk ...
Jun 29 17:27:50 ... writing SAindex to disk
Jun 29 17:28:01 ..... finished successfully
2021-06-29 17:28:02,778 - celescope.rna.mkref.build_star_index - INFO - done. time used: 1:29:39.520981
2021-06-29 17:28:02,778 - celescope.rna.mkref.write_config - INFO - start...
2021-06-29 17:28:02,779 - celescope.rna.mkref.write_config - INFO - done. time used: 0:00:00.000666
2021-06-29 17:28:02,779 - celescope.rna.mkref.run - INFO - done. time used: 1:29:59.984483
```
the celescope software's path is:
![image](https://user-images.githubusercontent.com/30076901/123904270-c819de80-d9a2-11eb-8183-131ed35db503.png)


Why did the error say `you need to build rna genome with 'celescope rna mkref' first`? I already have rna reference bulit.

Thanks!

**Comment by zhouyiqi91** [comment]
you need to run `celescope snp mkref` under the rna genomeDir.
 > AssertionError: .//celescope_genome.config not exist! You need to build rna genome with 'celescope rna mkref' first.

The error says that you need to have `celescope_genome.config` under current path when you run `celescope snp mkref`.

**Comment by Zymaniswenzai** [comment]
Hi, Dr. Zhou,
I prepared inpute files and ran the command line:
`multi_snp --mapfile my.mapfile.txt --genomeDir /home/lailab/disk/gjw/celescope_ref --thread 10 --mod shell --gene_list txp2gene1.txt --annovar_config annovar.config`

When I hit Enter, nothing comes out.
![image](https://user-images.githubusercontent.com/30076901/126742182-33543df6-1818-41f5-8977-c076a5c1be0c.png)

 I added a line - outdir/home/lailab/disk/gjw/multisnp
![image](https://user-images.githubusercontent.com/30076901/126742511-84ee1d2f-17e7-4e45-817f-2d1b0f6b6e26.png)
There's no result files here either.
`less annovar.config `
```
[ANNOVAR]
dir = /home/lailab/software/annovar 
db = /home/lailab/software/annovar/humandb  
buildver = hg38  
protocol = refGene,cosmic70  
operation = g,f
```

Thanks for your help!
Jingwen

**Comment by zhouyiqi91** [comment]
> `multi_snp --mapfile my.mapfile.txt --genomeDir /home/lailab/disk/gjw/celescope_ref --thread 10 --mod shell --gene_list txp2gene1.txt --annovar_config annovar.config`

It should output a shell script under `./shell/`. Would you please check if there was any file under `./log/` ?

**Comment by Zymaniswenzai** [comment]
there is no file under `/log`

![image](https://user-images.githubusercontent.com/30076901/126743902-04a5b2ea-dc3a-459e-9fe2-902f5122272c.png)


![image](https://user-images.githubusercontent.com/30076901/126743924-540b4e66-808c-41a8-9486-c200899a5913.png)

**Comment by zhouyiqi91** [comment]
What is your celescope version?

**Comment by Zymaniswenzai** [comment]
the version is 1.3.1

**Comment by zhouyiqi91** [comment]
It's weird that I can't reproduce the problem. 
![image](https://user-images.githubusercontent.com/30204951/126745843-8c7dba70-bb12-42b0-b3ab-0b83c602a478.png)

Remove the `--mod shell` argument and run again. Is there a `sjm.job` file in `./log` ?

**Comment by Zymaniswenzai** [comment]
```
job_begin
    name snpCalling_A3
    sched_options -w n -cwd -V -l vf=8g,p=10
    cmd source activate celescope; celescope snp snpCalling --outdir /home/lailab/disk/gjw/multisnp/A3/07.snpCalling --sample A3 --assay snp --thread 10 --genomeDir /home/lailab/disk/gjw/celescope_ref --gene_list txp2gene1.txt  --bam /home/lailab/disk/gjw/multisnp/A3/06.target_metrics/A3_filtered.bam --match_dir None 
job_end

job_begin
    name analysis_snp_A3
    sched_options -w n -cwd -V -l vf=8g,p=1
    cmd source activate celescope; celescope snp analysis_snp --outdir /home/lailab/disk/gjw/multisnp/A3/08.analysis_snp --sample A3 --assay snp --thread 10 --annovar_config annovar.config  --match_dir None --vcf /home/lailab/disk/gjw/multisnp/A3/07.snpCalling/A3_merged.vcf --CID_file /home/lailab/disk/gjw/multisnp/A3/07.snpCalling/A3_CID.tsv --variant_count_file /home/lailab/disk/gjw/multisnp/A3/07.snpCalling/A3_variant_count.tsv 
job_end

job_begin
    name merge_report
    sched_options -w n -cwd -V -l vf=1g,p=1
    cmd source activate celescope; python /home/lailab/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/merge_table.py --samples A3 --steps sample,barcode,cutadapt,consensus,star,featureCounts,target_metrics,snpCalling,analysis_snp --outdir /home/lailab/disk/gjw/multisnp
job_end

order barcode_A3 after sample_A3
order cutadapt_A3 after barcode_A3
order consensus_A3 after cutadapt_A3
order star_A3 after consensus_A3
order featureCounts_A3 after star_A3
order target_metrics_A3 after featureCounts_A3
order snpCalling_A3 after target_metrics_A3
order analysis_snp_A3 after snpCalling_A3
order merge_report after analysis_snp_A3
```

**Comment by Zymaniswenzai** [comment]
```
log_dir /home/lailab/disk/gjw/multisnp/log

job_begin
    name sample_A3
    sched_options -w n -cwd -V -l vf=1g,p=1
    cmd source activate celescope; celescope snp sample --outdir /home/lailab/disk/gjw/multisnp/A3/00.sample --sample A3 --assay snp --thread 10 --chemistry auto  --fq1 /home/lailab/disk/gjw/Ascite-3_R1.fq.gz 
job_end

job_begin
    name barcode_A3
    sched_options -w n -cwd -V -l vf=5g,p=1
    cmd source activate celescope; celescope snp barcode --outdir /home/lailab/disk/gjw/multisnp/A3/01.barcode --sample A3 --assay snp --thread 10 --chemistry auto --lowNum 2  --fq1 /home/lailab/disk/gjw/Ascite-3_R1.fq.gz --fq2 /home/lailab/disk/gjw/Ascite-3_R2.fq.gz 
job_end

job_begin
    name cutadapt_A3
    sched_options -w n -cwd -V -l vf=5g,p=1
    cmd source activate celescope; celescope snp cutadapt --outdir /home/lailab/disk/gjw/multisnp/A3/02.cutadapt --sample A3 --assay snp --thread 10 --minimum_length 20 --nextseq_trim 20 --overlap 10 --insert 150  --fq /home/lailab/disk/gjw/multisnp/A3/01.barcode/A3_2.fq 
job_end

job_begin
    name consensus_A3
    sched_options -w n -cwd -V -l vf=5g,p=1
    cmd source activate celescope; celescope snp consensus --outdir /home/lailab/disk/gjw/multisnp/A3/03.consensus --sample A3 --assay snp --thread 10 --threshold 0.5  --fq /home/lailab/disk/gjw/multisnp/A3/02.cutadapt/A3_clean_2.fq 
job_end

job_begin
    name star_A3
    sched_options -w n -cwd -V -l vf=30g,p=10
    cmd source activate celescope; celescope snp star --outdir /home/lailab/disk/gjw/multisnp/A3/04.star --sample A3 --assay snp --thread 10 --genomeDir /home/lailab/disk/gjw/celescope_ref --outFilterMultimapNmax 1 --starMem 30  --consensus_fq  --fq /home/lailab/disk/gjw/multisnp/A3/03.consensus/A3_consensus.fq 
job_end

job_begin
    name featureCounts_A3
    sched_options -w n -cwd -V -l vf=5g,p=10
    cmd source activate celescope; celescope snp featureCounts --outdir /home/lailab/disk/gjw/multisnp/A3/05.featureCounts --sample A3 --assay snp --thread 10 --gtf_type exon --genomeDir /home/lailab/disk/gjw/celescope_ref  --input /home/lailab/disk/gjw/multisnp/A3/04.star/A3_Aligned.sortedByCoord.out.bam 
job_end

job_begin
    name target_metrics_A3
    sched_options -w n -cwd -V -l vf=2g,p=1
    cmd source activate celescope; celescope snp target_metrics --outdir /home/lailab/disk/gjw/multisnp/A3/06.target_metrics --sample A3 --assay snp --thread 10 --gene_list txp2gene1.txt  --bam /home/lailab/disk/gjw/multisnp/A3/05.featureCounts/A3_Aligned.sortedByCoord.out.bam.featureCounts.bam --match_dir None 
job_end

job_begin
    name snpCalling_A3
    sched_options -w n -cwd -V -l vf=8g,p=10
    cmd source activate celescope; celescope snp snpCalling --outdir /home/lailab/disk/gjw/multisnp/A3/07.snpCalling --sample A3 --assay snp --thread 10 --genomeDir /home/lailab/disk/gjw/celescope_ref --gene_list txp2gene1.txt  --bam /home/lailab/disk/gjw/multisnp/A3/06.target_metrics/A3_filtered.bam --match_dir None 
job_end

job_begin
    name analysis_snp_A3
    sched_options -w n -cwd -V -l vf=8g,p=1
    cmd source activate celescope; celescope snp analysis_snp --outdir /home/lailab/disk/gjw/multisnp/A3/08.analysis_snp --sample A3 --assay snp --thread 10 --annovar_config annovar.config  --match_dir None --vcf /home/lailab/disk/gjw/multisnp/A3/07.snpCalling/A3_merged.vcf --CID_file /home/lailab/disk/gjw/multisnp/A3/07.snpCalling/A3_CID.tsv --variant_count_file /home/lailab/disk/gjw/multisnp/A3/07.snpCalling/A3_variant_count.tsv 
job_end

job_begin
    name merge_report
    sched_options -w n -cwd -V -l vf=1g,p=1
    cmd source activate celescope; python /home/lailab/miniconda3/envs/celescope/lib/python3.6/site-packages/celescope/tools/merge_table.py --samples A3 --steps sample,barcode,cutadapt,consensus,star,featureCounts,target_metrics,snpCalling,analysis_snp --outdir /home/lailab/disk/gjw/multisnp
job_end

order barcode_A3 after sample_A3
order cutadapt_A3 after barcode_A3
order consensus_A3 after cutadapt_A3
order star_A3 after consensus_A3
order featureCounts_A3 after star_A3
order target_metrics_A3 after featureCounts_A3
order snpCalling_A3 after target_metrics_A3
order analysis_snp_A3 after snpCalling_A3
order merge_report after analysis_snp_A3
```

**Comment by zhouyiqi91** [comment]
Hi，@Zymaniswenzai, the lastest release of CeleScope(v1.6.0) has updated the variant calling pipeline. See https://github.com/singleron-RD/CeleScope/blob/master/docs/snp/multi_snp.md for details.
