### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by panzzz515** [singleron-RD/CeleScope#37]
![ca3ed9e6abf3bb9593773d116b4f1d9](https://user-images.githubusercontent.com/77045227/123721941-eb1c9380-d8b9-11eb-849a-e9fcdd0820be.jpg)

**Comment by zhouyiqi91** [comment]
Where do you get celescope version 1.0? The oldest release version of celescope on pypi is 1.1.0. 
![image](https://user-images.githubusercontent.com/30204951/123722684-6894d380-d8bb-11eb-9600-ed17271cd3aa.png)

It is recommended to use the lastest version 1.3.1.
