### ISSUE TITLE
Report template

### ISSUE THREAD

**Issue by TeaByrd** [singleron-RD/CeleScope#46]
Hello guys,

I'd like to include an improved scRNA Report template in the CeleScope pipeline and do not know where to exactly put it.

I know according to the /workflow/scRNA_analysis/workflow.wdl script, it a runs a program called scrna_report including these lines:
```
....
    elif [ "~{language}" = "English" ]; then
       cp ~{report_temp}  "~{targetFolder}/~{sample_name}_RNA_report/src/web_summary.html"
       **perl /opt/scRNA_Report/Report/Eng.Singleron/report.V2.0.1.pl** \
            -indir  ~{targetFolder} \
            -projectID ~{projectID} \
            -type SCOPEv1 \
            -prefix "~{sample_name}_RNA" \
            -sample ~{sample_name} \
            -rmd  /opt/scRNA_Report/Report/Eng.Singleron/report_summary.rmd \
            -pdf /opt/conda/bin/wkhtmltopdf \
            -species ~{species} \
            -rmarkdown  /opt/scRNA_Report/Report/rmarkdown
    fi
    cd  ~{targetFolder}
    tar -zcf "~{sample_name}_RNA_report.tar.gz" "~{sample_name}_RNA_report"
    tar -zcf "~{sample_name}_RNA_result.tar.gz" "~{sample_name}_RNA_result"
```
....

So I think the template is accessed by the perl script `report.V2.0.1.pl` in `/opt/scRNA_Report/Report/Eng.Singleron`.
But I can't find it neither on the GitHub, nor in my celescope environment. Can you help?

I other words - where is the report template ?

Best regards,
Thomas

**Comment by zhouyiqi91** [comment]
Actually, the template and the perl script are not part of CeleScope. You can think of them as another pipeline build on the output of CeleScope. 
You can ask the question in this repo: https://github.com/SingleronBio/workflow
