### ISSUE TITLE
each single cell's sequencing depth

### ISSUE THREAD

**Issue by Zymaniswenzai** [singleron-RD/CeleScope#64]
Dear Dr.Zhou,
  Hi, I extracted every single cell's `.bed` file in the `.bam` file, which contained all cells, based on the unique UMI marker. And I want to know how to get each cell's sequencing depth? 
  Thanks for any help!

 Jingwen

**Comment by zhouyiqi91** [comment]
1. What's your purpose of getting the `sequencing depth` for each cell? Normally the average sequencing depth(i.e. Mean reads per cell) is used to determine whether the `sequencing depth`  is sufficient or not.

2. If you want to get the `UMI depth per cell`, just sum the UMIs of each cell in the expression matrix. If `Read depth per cell` is what you want, you need to write a script to count the read of each cell in the `bam` file.
