### ISSUE TITLE
issue to merge matrix files from different runs

### ISSUE THREAD

**Issue by gangcai** [singleron-RD/CeleScope#81]
For the output of cellranger, it is easy to merge matrix files from different samples, due to the same row names of the matrix (all the genes were used). Is it possible for celescope to generate this type of matrix files with the same row names (the same genes.tsv) for different runs?

**Comment by zhouyiqi91** [comment]
You are right that CeleScope only output detected genes. And in the current version there is no function to output all the genes.
But I think it's feasible to use Seurat to merge two or more matrcies.
https://satijalab.org/seurat/articles/merge_vignette.html

**Comment by zhouyiqi91** [comment]
Starting from celescope 1.11.0, all genes (even if the expression level is 0) will be added to `genes.tsv`.
If you want to add genes whose expression level is 0 to the `genes.tsv` of the previous version, you can use the following script
https://github.com/singleron-RD/CeleScope/blob/master/scripts/add_zero_count_genes.py
