### ISSUE TITLE
No file "BCR_UMI_count_filtered.tsv"

### ISSUE THREAD

**Issue by ghost** [singleron-RD/CeleScope#95]
BCR data analysis pipline was broken becasuse of the lost file "BCR_UMI_count_filtered.tsv".

Because of the data was from BGI platform, and in this way， ‘--not_consensus’ was added to the file

Will this be the question?

waitting for any words, thanks so much!

**Comment by zhouyiqi91** [comment]
I can not reproduce the problem. Please attach the log file.

**Comment by ghost** [comment]
OK, thanks so much!
I have find the source of this problem: 
The celescope command "multi_vdj --not_consensus" failed to produce the catalogue "03.consensus" which was necessary to create the file "BCR_UMI_count_filtered.tsv"
