### ISSUE TITLE
dynascope question

### ISSUE THREAD

**Issue by lgmp315** [singleron-RD/CeleScope#98]
Hi bro. Do I need to construct a reference genome for Dynascope's Multi_? What species does the test data correspond to？

**Comment by pigraul** [comment]
It is Mus musculus .

Yes, you need to build the genome index as mentioned  in the [Quick start](https://github.com/singleron-RD/CeleScope/blob/master/docs/quick_start.md) .

**Comment by lgmp315** [comment]
Just use this two links as mentioned in Quick start？
wget ftp://ftp.ensembl.org/pub/release-99/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz
wget ftp://ftp.ensembl.org/pub/release-99/gtf/mus_musculus/Mus_musculus.GRCm38.99.gtf.gz

**Comment by zhouyiqi91** [comment]
> Just use this two links as mentioned in Quick start？ wget ftp://ftp.ensembl.org/pub/release-99/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz wget ftp://ftp.ensembl.org/pub/release-99/gtf/mus_musculus/Mus_musculus.GRCm38.99.gtf.gz

Yes. Dynascope's reference genome is the same as the genome used in scRNA-Seq analysis.

**Comment by lgmp315** [comment]
tahnks bro!

**Comment by lgmp315** [comment]
![doc1](https://user-images.githubusercontent.com/98027401/155257475-716faa4d-ecc9-4364-ae01-073eee7d19d7.png)
![doc2](https://user-images.githubusercontent.com/98027401/155257480-6ba99000-eb84-4269-9197-e9922a018afa.png)
Hey dude, sorry for disturbing again, Im not quite understand whether I link the correct doc with dyna_script. and I wonder where should I put the **a1.vcf** file?
another question is what is the control.PosTag.csv? is it record the background mutation ratio from normal tissue?

**Comment by pigraul** [comment]
Yes, the control.PosTag.csv recorded the background mutations from normal tissue. If you have unlabeled scRNA-seq data from GEXSCOPE Kit (Singleron), you can use this multi_dynaseq pipeline to generate this file ( just set the first three columns in mapfile). 

The a1.vcf is an alternate file for the csv file.  Considering VCF is the standard file format for storing variation data and is the output format for most variation calling software, so users can provide vcf file as the background mutation file in mapfile.

**Comment by lgmp315** [comment]
Hi bro!
Can the dynaSCOPE data be analyzed together with bulk RNA data?

**Comment by lgmp315** [comment]
Hi bro!
Can the dynaSCOPE data be analyzed together with bulk RNA data and which argument to add?

**Comment by pigraul** [comment]
Sorry, this pipeline can not analysis bulk RNA data right now.

If you want to use bulk RNA data to call background mutations, we recommend use the GATK pipeline ( https://gatk.broadinstitute.org/hc/en-us/articles/360035531192-RNAseq-short-variant-discovery-SNPs-Indels- ) to generate the VCF file, and write the vcf file into the mapfile.

**Comment by lgmp315** [comment]
OK，I see，thank u very much

**Comment by lgmp315** [comment]
> Yes, the control.PosTag.csv recorded the background mutations from normal tissue. If you have unlabeled scRNA-seq data from GEXSCOPE Kit (Singleron), you can use this multi_dynaseq pipeline to generate this file ( just set the first three columns in mapfile).
> 
> The a1.vcf is an alternate file for the csv file. Considering VCF is the standard file format for storing variation data and is the output format for most variation calling software, so users can provide vcf file as the background mutation file in mapfile.

Hi bro，how to make PosTag.csv. should the mapfile make like multi_rna and use the rna fastqs path?
